# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ev.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ev.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x65v.proto\x12\x08\x65v_sales\"T\n\rUploadRequest\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x12.ev_sales.FileInfoH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"\x1c\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"0\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x80\x01\n\x12SalesFilterRequest\x12:\n\x07\x66ilters\x18\x01 \x03(\x0b\x32).ev_sales.SalesFilterRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1f\n\nSalesReply\x12\x11\n\tsales_xml\x18\x01 \x03(\t2\x95\x01\n\x07\x45VSales\x12\x46\n\x10GetSalesFiltered\x12\x1c.ev_sales.SalesFilterRequest\x1a\x14.ev_sales.SalesReply\x12\x42\n\rUploadDataset\x12\x17.ev_sales.UploadRequest\x1a\x16.ev_sales.UploadStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ev_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALESFILTERREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_SALESFILTERREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_UPLOADREQUEST']._serialized_start=22
  _globals['_UPLOADREQUEST']._serialized_end=106
  _globals['_FILEINFO']._serialized_start=108
  _globals['_FILEINFO']._serialized_end=136
  _globals['_UPLOADSTATUS']._serialized_start=138
  _globals['_UPLOADSTATUS']._serialized_end=186
  _globals['_SALESFILTERREQUEST']._serialized_start=189
  _globals['_SALESFILTERREQUEST']._serialized_end=317
  _globals['_SALESFILTERREQUEST_FILTERSENTRY']._serialized_start=271
  _globals['_SALESFILTERREQUEST_FILTERSENTRY']._serialized_end=317
  _globals['_SALESREPLY']._serialized_start=319
  _globals['_SALESREPLY']._serialized_end=350
  _globals['_EVSALES']._serialized_start=353
  _globals['_EVSALES']._serialized_end=502
# @@protoc_insertion_point(module_scope)
