# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ev_pb2 as ev__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ev_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EVSalesStub(object):
    """====================================================================
    Definição do Serviço
    ====================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSalesFiltered = channel.unary_unary(
                '/ev_sales.EVSales/GetSalesFiltered',
                request_serializer=ev__pb2.SalesFilterRequest.SerializeToString,
                response_deserializer=ev__pb2.SalesReply.FromString,
                _registered_method=True)
        self.UploadDataset = channel.stream_unary(
                '/ev_sales.EVSales/UploadDataset',
                request_serializer=ev__pb2.UploadRequest.SerializeToString,
                response_deserializer=ev__pb2.UploadStatus.FromString,
                _registered_method=True)


class EVSalesServicer(object):
    """====================================================================
    Definição do Serviço
    ====================================================================
    """

    def GetSalesFiltered(self, request, context):
        """Método 1: Consulta de filtros (existente)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDataset(self, request_iterator, context):
        """Método 2: Dataset Upload (Obrigatório para o Servidor Dinâmico)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EVSalesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSalesFiltered': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesFiltered,
                    request_deserializer=ev__pb2.SalesFilterRequest.FromString,
                    response_serializer=ev__pb2.SalesReply.SerializeToString,
            ),
            'UploadDataset': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadDataset,
                    request_deserializer=ev__pb2.UploadRequest.FromString,
                    response_serializer=ev__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ev_sales.EVSales', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ev_sales.EVSales', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EVSales(object):
    """====================================================================
    Definição do Serviço
    ====================================================================
    """

    @staticmethod
    def GetSalesFiltered(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ev_sales.EVSales/GetSalesFiltered',
            ev__pb2.SalesFilterRequest.SerializeToString,
            ev__pb2.SalesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDataset(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ev_sales.EVSales/UploadDataset',
            ev__pb2.UploadRequest.SerializeToString,
            ev__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
